import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import "../styles/globals.css";
import Providers from "@/providers/Providers";

const alexandria = Alexandria({
  variable: "--font-alexandria",
  subsets: ["latin"],
  display: "auto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${alexandria.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
